### PR TITLE
Fix don't gzip server-sent events

### PR DESCRIPTION
**Pull request by nickbug**
Should check Accept not Content-Type.

### CODE REVIEW

**Comment by ss89** [comment]
fixes #45

**Comment by ss89** [comment]
@appleboy you seem to be the most active guy on this repo recently. Would you approve and merge this?

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
@ss89 merged

**Comment by appleboy** [comment]
bump to https://github.com/gin-contrib/gzip/releases/tag/v0.0.4

**Comment by ss89** [comment]
Thanks a lot 🙂

**Comment by fanybook** [comment]
@appleboy 

https://github.com/gin-gonic/gin/issues/4213

1.0.0 has this problem too

**Pull request merged**
