### PR TITLE
Use gopkg.in

### PR DESCRIPTION
**Pull request by tleb**

### CODE REVIEW

**Comment by tboerger** [comment]
It's still referring to gin-gonic/contrib

**Comment by tleb** [comment]
Fixed :)

**Comment by tboerger** [comment]
@javierprovecho how do we want to handle newer versions of gin? Within another branch?

**Comment by tboerger** [comment]
Maybe we want to provide these middlewares also via gopkg.in?

**Comment by appleboy** [comment]
@tboerger Yes. I will bump new version for all middleware via gopkg.in

**Comment by tmm1** [comment]
After this change I can no longer use this middleware unless I also switch to gopkg.in imports for gin. I don't want to do this, as I am using the [glide package manager](https://glide.sh) already to pick a specific revision of gin that I want to use.

>cannot use gzip.Gzip(gzip.DefaultCompression) (type "gopkg.in/gin-gonic/gin.v1".HandlerFunc) as type "github.com/gin-gonic/gin".HandlerFunc in argument to r.Use

IMHO users should not be forced to use gopkg.in, especially considering that it was recently [broken for many weeks](https://github.com/niemeyer/gopkg/issues/50) when using newer versions of git.

**Comment by tleb** [comment]
> IMHO users should not be forced to use gopkg.in

Gin recommends using `gopkg.in` and most packages around it use it.

Maybe create a branch for each solution?

**Comment by robbiet480** [comment]
Pretty sure this is invalid behavior as per these issues:

https://github.com/gin-gonic/contrib/issues/133
https://github.com/gin-contrib/sessions/pull/9
https://github.com/gin-gonic/gin/issues/828

and [this comment](https://github.com/gin-contrib/sessions/pull/9#issuecomment-286743525).

**Pull request merged**
